frompathlibimportPath


BASE_DIR=Path(__file__).parent
OUTPUT_DIR=BASE_DIR/"outputs"
OUTPUT_DIR.mkdir(exist_ok=True)


YOLO_MODEL="yolov8n.pt"
CONFIDENCE_THRESHOLD=0.3
IOU_THRESHOLD=0.45


OCR_LANGUAGES=['en']
OCR_GPU=False


MAX_IMAGE_SIZE_MB=20.0
MAX_VIDEO_SIZE_MB=200.0
ALLOWED_IMAGE_TYPES={".jpg",".jpeg",".png",".bmp",".webp"}
ALLOWED_VIDEO_TYPES={".mp4",".avi",".mov",".mkv",".webm"}


VIDEO_SKIP_FRAMES=2
MAX_VIDEO_FRAMES=500

ANNOTATED_COLOR=(0,255,80)
TEXT_COLOR=(255,255,255)
FONT_SCALE=0.8
FONT_THICKNESS=2
